{ socket: 
   { _handle: 
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 395,
     bytesWritten: 0,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { connections: 2,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        bytesRead: 0,
        bytesWritten: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        ondrain: [Function],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
        _events: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  connection: 
   { _handle: 
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 395,
     bytesWritten: 0,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { connections: 2,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        bytesRead: 0,
        bytesWritten: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        ondrain: [Function],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
        _events: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  httpVersion: '1.1',
  complete: false,
  headers: 
   { host: '127.0.0.1:8124',
     connection: 'keep-alive',
     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11',
     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
     'accept-encoding': 'gzip,deflate,sdch',
     'accept-language': 'en-US,en;q=0.8',
     'accept-charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3' },
  trailers: {},
  readable: true,
  url: '/?hej=hopp',
  method: 'GET',
  statusCode: null,
  client: 
   { _handle: 
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 395,
     bytesWritten: 0,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { connections: 2,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        bytesRead: 0,
        bytesWritten: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        ondrain: [Function],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
        _events: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  upgrade: false }
{ socket: 
   { _handle: 
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 732,
     bytesWritten: 119,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { connections: 2,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        bytesRead: 0,
        bytesWritten: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        ondrain: [Function],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
        _events: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  connection: 
   { _handle: 
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 732,
     bytesWritten: 119,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { connections: 2,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        bytesRead: 0,
        bytesWritten: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        ondrain: [Function],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
        _events: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  httpVersion: '1.1',
  complete: false,
  headers: 
   { host: '127.0.0.1:8124',
     connection: 'keep-alive',
     accept: '*/*',
     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11',
     'accept-encoding': 'gzip,deflate,sdch',
     'accept-language': 'en-US,en;q=0.8',
     'accept-charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3' },
  trailers: {},
  readable: true,
  url: '/favicon.ico',
  method: 'GET',
  statusCode: null,
  client: 
   { _handle: 
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _pendingWriteReqs: 0,
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 732,
     bytesWritten: 119,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     server: 
      { connections: 2,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        bytesRead: 0,
        bytesWritten: 0,
        allowHalfOpen: true,
        writable: true,
        readable: true,
        server: [Object],
        ondrain: [Function],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
        _events: [Object],
        ondata: [Function],
        onend: [Function] },
     _idlePrev: 
      { _idleNext: [Circular],
        _idlePrev: [Object],
        ontimeout: [Function] },
     _idleStart: Wed, 22 Feb 2012 18:14:25 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: 
      { output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        _hasBody: true,
        _trailer: '',
        finished: false,
        socket: [Circular],
        connection: [Circular],
        _events: [Object] } },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  upgrade: false }
